// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unrgxsawwnytcgitnohd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucmd4c2F3d255dGNnaXRub2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMzUzMTgsImV4cCI6MjA4NjkxMTMxOH0.IrNpRYBEdbVGycEzNGOwODSHHO3Qb0_hdctv0vcOuEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});